default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml # Checks yaml files for parseable syntax.
      - id: check-json # Checks json files for parseable syntax.
      - id: check-added-large-files
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: requirements-txt-fixer # Sorts entries in requirements.txt

  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile
          - black
          - --line-length
          - "120"
          - -m
          - "3"
          - --tc
          - --skip-glob
          - "^((?!py$).)*$"
          - --float-to-top
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args:
          - --line-length
          - "120"
          - --target-version
          - "py37"
          - --include
          - '\.py$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-cachetools
          - types-filelock
          - types-PyYAML
          - types-redis
          - types-requests
          - types-setuptools
          - types-toml
          - attrs
          - pydantic
        args: [--allow-redefinition, --ignore-missing-imports, --exclude=tests.*]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
